language: java
sudo: required
services:
- docker
env:
  global:
  - REGISTRY_USER=pjotre86
  # REGISTRY_PASS
  - secure: HP1WQx7TfmmKexX4smXillcGdu+OPqSfM8Jd4DUYaGfl26/K32YA3gC9OeWNqhWr7OGu/3ZBCFvTJUPpN+bJRKmTOE0DbBK/pTAANbDG5nVHn70YnvoE4GA0tNJxn/aDtllQ98FA4Nz8jaDDJOFY4jSqVls4OCWAlF+sfCI6cC/oGKhtCVpc5V03g1Mg2ihEymBXslTYrszH82XAnXQYvJte5cUyjV75khoNHTxTAe0/tHBBo1YfWejb5fHvgAaVca7kVGEvygynTueYm3WPTnoJPTWTSMJs0fJtAEg0A9HKXoABxAGM0hqmv3F5hx7xCe/xh5bxv/Uhrbu4oHPsMU9pu2obl+NFIJ5NmGcfCN4v74y+YBj0eo/NFxFcmAXl3q83sp5N8b7tmjUNur+SkXHTNsTreOgpg75WSw70a9/OztBDbMiuiJam/mR57HZRDDpEOdbpTwD7JlUugWRXVFTMeK7yKn+uOx7505GGg/Hy43KCA62wn1U/6ZEO53FtCS5mp/aKo1gH32c5Rww80Lk8jbhQgz+KLoKneI9HqwqQswNeRJ1sCpW0Di/xgrNSRmSbHQYdrIjuFB0lV5P1GfAB9L+1Cn+JrtNCQhMUiQIVJ11zLIpYGU4jBuaANNl0tu2j8yIjsx/d3CX+igNFf9HNarkcChoIYI6XXHnZ7X0=
  # GH_TOKEN
  - secure: "SBStldo+MlhhNV3GQfo0kY/2LrucH4T9ZbUpnFCygdQX+FMw1Lj7Ni1zHRySQBR1LuwhRhMJ1E93LcHwKKlpym8JSsX/jjIpgfXVW9+kAj17W+yxc/ohwVChVLBH0pR1xzwlsQg899I76XR+xrGYpiUI4QF/AzExMhOW/8OHHcXt/n5LCGTG3OsnLED2Xj224bpHYo+jEmHGceLEru5pg/+bKz7/tW3h4xQcAR5Eo/lzK0Py8hHJPNvxcl8qtT729EYvblTF1CZVHTf8VPrVH8hnEnAD/rRoXMCm9ZN8vz7je0XKMPmfcZdpwPlTpbkyey2KLf74hYgllc3GEDXupWpVyI4KdJWf+HoQMKibfk2HvOaB4l1RLTgrMIV0Tz7iMRekiT+aFK4oLfNPaFr1xw70rBG02FU5Y//GJfIBUo9n8sMBhtmrv44svk/4XiU4CSBx9J/zehwBA+PbiC2xJQPGc6N6hvrz+BLFL7K11jSA7+58SzjmftXbqD8hiw05IrdVwDkL2Wa1P+XiDq/xRmY2k3tn0Rn91G+5tjl2snFM8p2SjvaMzbWIJaK8Y4sziKVgmSSDFYuc/sObHnSD2o0IzAG98yZkdSoStxzLBRHgPcdc1Wez+sYnlms0RalBfH/fHChg4LFc5ZCquqLswHFIA0lmJ57GLLyU6hNXSVI="

before_script:
  - nvm install lts/*
  - npm i @conveyal/maven-semantic-release
  - npx semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release --skip-maven-deploy
  - docker pull corphub/corphub-backend || true
script:
- docker build --cache-from corphub/corphub-backend --tag corphub/corphub-backend .
after_script:
- docker images
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push corphub/corphub-backend
  on:
    branch: master